import React from 'react'

const ChatSection = () => {
  return (
    <div>
         `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
            `hello there`
    </div>
  )
}

export default ChatSection